version: "2.2"

services:
  mysql:
    image: mysql:8.0
    labels:
      - "app=petclinic"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysql
  #   environment:
  #     - APP_HOME=/app
  #     - LOG_HOME=/app/logs
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
