apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      initContainers:
      - name: init-logs
        image: busybox
        command: ['sh', '-c', 'mkdir -p /logs && chown -R 999:999 /logs && chmod -R 775 /logs']
        volumeMounts:
        - name: log-volume
          mountPath: /logs
      containers:
      - name: petclinic
        image: dlsrks1218/petclinic:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: log-volume
          mountPath: /app/logs
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
        securityContext:
          runAsUser: 999
      terminationGracePeriodSeconds: 30
      volumes:
      - name: log-volume
        hostPath:
          path: /logs
          type: DirectoryOrCreate
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
